name: smart_children
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  native_video_view:
  flutter_spinkit: "^4.1.2"
  rflutter_alert: ^1.1.0
  speech_to_text: ^2.5.0
  avatar_glow: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - videos/
  - images/
